# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true
      - run: git push origin a47abf1b7a7c7a9db4e9f1be9c827e549cc113e0:refs/tags/v2.0
      - uses: jessehouwing/actions-semver-checker@copilot-add-v2-release-features
        with:
          auto-fix: true
          check-minor-version: true
          check-releases: error
          check-release-immutability: none
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Runs a single command using the runners shell
      - uses: jessehouwing/sample-composite-action@v2
        with:
          who-to-greet: nospt
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: dist
          path: .
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: tests
          path: .
      
  unittest:
    runs-on: ubuntu-latest 
    needs: [build]
    steps:
      - uses: actions/checkout@v6
      
  deploy:
    runs-on: ubuntu-latest 
    needs: [build, unittest]
    environment: test

    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7.0.0
        with:
          name: tests
